### PR TITLE
Add Android TV intent category

### PR DESCRIPTION
**Pull request by tasomaniac**
- This will make it selectable in an Android TV.
- Banner warning is ignored, it would be the best if we have both icon and a banner.

tv

### CODE REVIEW

**Comment by xrigau** [comment]
💯  now we just need to reinstall on all the clients :trollface:

**Comment by frapontillo** [comment]
@xrigau I can do it in London, do I need instructions?

**Comment by xrigau** [comment]
it should be a matter of compiling the app and doing `adb connect $IP_ADDRESS` to each of the devices and install the app

**Comment by tasomaniac** [comment]
Not really for Amazon FireTV devices. I believe those are different. 
I only saw one NVidia Shield in London Cave. Maybe that can be re-installed.

**Comment by xrigau** [comment]
I've used adb connect w/ the fire tv sticks and worked well :)

**Pull request merged**
