### PR TITLE
Add project diagram

### PR DESCRIPTION
**Pull request by lgvalle**
dashboard-containers

Adds a high level diagram to understand how components relate to each other

### CODE REVIEW

**Comment by ouchadam** [comment]
looking good 👍

**Review by ouchadam — APPROVED** [review]

**Comment by takecare** [comment]
couple of Qs/comments:

- `chrome OS`
- why the arrow going both ways on between `plugin` and `server`
- maybe worth to add something on the arrow going from `server` to `website`?

**Comment by lgvalle** [comment]
1. Thx, fixing it
2. So, the diagram doesn't try to represent accurately what happens in terms of connections, but rather the components involved and how talks with whom. That been said, this tries to represent the fact that each plugin is a little server itself. If I understand the setup correctly we have a main server talking with little small servers (the plugins)
3. On it 👍

**Comment by lgvalle** [comment]
Updated to:
dashboard-containers

**Review by takecare — APPROVED** [review]

**Pull request merged**
