### PR TITLE
PT-394: Make sure we call the done method inside the catch block

### PR DESCRIPTION
**Pull request by florianmski**
Tracked in JIRA by [PT-394](https://novoda.atlassian.net/browse/PT-394)

### Scope of the PR

As per @frapontillo comment https://github.com/novoda/dashboards/pull/49#discussion_r96042625 we have multiple tests in the project that might not break if we don't get the expected result.
Fix is to include the call to done in the catch block.

### CODE REVIEW

**Comment by florianmski** [comment]
Retest this please

**Comment by florianmski** [comment]
Retest this please

**Comment by florianmski** [comment]
Retest this please

**Comment by florianmski** [comment]
Retest this please

**Comment by frapontillo** [comment]
So we're relying on Jasmine to timeout if `done` is not called rather than failing explicitly? It's ok to me, just making sure. 👍

**Comment by florianmski** [comment]
@frapontillo yep 👍

**Comment by frapontillo** [comment]
Fix the Gradle issue and I shall ship it.

**Comment by florianmski** [comment]
Retest this please

**Pull request merged**
